### ISSUE TITLE
Issue with a csv file

### ISSUE THREAD

**Issue by ericemc3** [tobilg/sql-workbench#1]
No result here:
```
create table rappelconso as 
from read_csv_auto('https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/rappelconso0/exports/csv?lang=fr&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B') ;

FROM rappelconso LIMIT 10;
```

I guess a weird column name for the first field.

**Comment by tobilg** [comment]
It look like there's a problem with the header formatting in the file. The following query works:

```sql
create table rappelconso as from read_csv_auto('https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/rappelconso0/exports/csv?timezone=Europe%2FBerlin&delimiter=%3B');
```

https://sql-workbench.com/#queries=v0,create-table-rappelconso-as-from-read_csv_auto('https%3A%2F%2Fdata.economie.gouv.fr%2Fapi%2Fexplore%2Fv2.1%2Fcatalog%2Fdatasets%2Frappelconso0%2Fexports%2Fcsv%3Ftimezone%3DEurope%252FBerlin%26delimiter%3D%253B')~

If you add the `normaliue_names` flag to the `read_csv_auto()` config, this works as well with the original request:

```sql
from read_csv_auto('https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/rappelconso0/exports/csv?lang=fr&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B', normalize_names = true);
```

https://sql-workbench.com/#queries=v0,from-read_csv_auto('https%3A%2F%2Fdata.economie.gouv.fr%2Fapi%2Fexplore%2Fv2.1%2Fcatalog%2Fdatasets%2Frappelconso0%2Fexports%2Fcsv%3Flang%3Dfr%26timezone%3DEurope%252FBerlin%26use_labels%3Dtrue%26delimiter%3D%253B'%2C-normalize_names-%3D-true)~

**Comment by ericemc3** [comment]
Thanks !
