### ISSUE TITLE
Failure if column is a list

### ISSUE THREAD

**Issue by alexanderhupfer** [tobilg/sql-workbench#11]
<img width="1292" alt="Screenshot 2024-04-04 at 23 29 44" src="https://github.com/tobilg/sql-workbench/assets/5372632/0c834d47-1d34-405d-90de-7775c6fdce2a">

Column type seem to be a list

**Comment by tobilg** [comment]
Support for displaying complex data types has landed earlier today. Please recheck @alexanderhupfer Thanks!
