### ISSUE TITLE
Different results in Firefox and Chrome

### ISSUE THREAD

**Issue by liquidcarbon** [tobilg/sql-workbench#14]
Hi, me again with the [isotopes](https://sql-workbench.com/#queries=v0,select-Symbol%2C-Number%2C-Mass%2C-Abundance-from-%27https%3A%2F%2Fraw.githubusercontent.com%2Fekwan%2Fcctk%2Fmaster%2Fcctk%2Fdata%2Fisotopes.csv%27~) :) 
Seems like Firefox is not playing along with something.
Thorium(Chrome) on left, Firefox on right.

![image](https://github.com/tobilg/sql-workbench/assets/47034358/f900b8cf-cad5-4d0e-8851-329c9049cd71)

![image](https://github.com/tobilg/sql-workbench/assets/47034358/3c225d86-a5cb-4149-8af7-b5253c9011bf)

**Comment by tobilg** [comment]
Works for me on MacOS, can you please recheck @liquidcarbon? Thanks!
