### ISSUE TITLE
Struct fields not displaying

### ISSUE THREAD

**Issue by mskyttner** [tobilg/sql-workbench#17]
When reading JSON from a URL it appears that fields of type "json" works but fields of type "struct" do not appear.

Therefore this works in sql-workbench (since all struct fields are excluded).

```
select #1, #2, #3, #4, #6, #7, #8, #11, #12, #13, #14, #16, #17, #18, #22, #23 
from read_json_auto('http://localhost/someapi?offset=0&limit=100');
```
The duckdb CLI works without any need to exclude the struct fields in the query.

```
duckdb -c "select #5, #9, #10, #15, #19, #20, #21 from read_json_auto('http://localhost/gdp/v1/ansokningar?limit=100&franBeslutDatum=2021-06-29&tillBeslutDatum=2021-08-29')"
┌──────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┬──────────────────────┬──────────────────────────────────────────────────────────────────────────┐
│         lank         │    organisationer    │       personer       │        beslut        │      utlysning       │       program        │                              hallbarhetsmal                              │
│ struct(href varcha…  │ struct(namn varcha…  │ struct(namn varcha…  │ struct(datum date,…  │ struct(diarienumme…  │ struct(diarienumme…  │                 struct(namn varchar, namneng varchar)[]                  │
├──────────────────────┼──────────────────────┼──────────────────────┼──────────────────────┼──────────────────────┼──────────────────────┼──────────────────────────────────────────────────────────────────────────┤
│ {'href': /v1/ansok…  │ [{'namn': Ej öppna…  │ [{'namn': NULL, 'O…  │ {'datum': 2021-06-…  │ {'diarienummer': 2…  │ {'diarienummer': 2…  │                                                                          │

```

**Comment by tobilg** [comment]
Thanks for reporting, I saw this myself as well... The shell and the CLI are just casting specific data types to varchars, so eventually I'll do that too.

See https://github.com/duckdb/duckdb-wasm/blob/main/packages/duckdb-wasm-shell/crate/src/arrow_printer.rs#L89

**Comment by tobilg** [comment]
I opened an issue with the used library as well: https://github.com/finos/perspective/issues/2711

**Comment by tobilg** [comment]
SQL Workbench was updated to be able to display complex data types as well. Please check and eventually close this issue @mskyttner. Thanks!

**Comment by mskyttner** [comment]
Thanks for looking into this! And while doing that, I hope you don't get discouraged by testy attitudes from various maintainers of upstream libraries...

I quickly tested with the same data source I used when I discovered this issue with and got this in the JS console:

```
Table initialization failed: Error: Abort(): Could not load arrow column of type `struct`
ff73d57b-adba-46e2-8ae1-37803fb3de3d:21:37102
    table blob:https://sql-workbench.com/ff73d57b-adba-46e2-8ae1-37803fb3de3d:21
    process blob:https://sql-workbench.com/ff73d57b-adba-46e2-8ae1-37803fb3de3d:21
    q blob:https://sql-workbench.com/ff73d57b-adba-46e2-8ae1-37803fb3de3d:21
```

My query works in the duckdb CLI and was this one:

```
duckdb -c "from read_json_auto('http://localhost/gdp/v1/ansokningar?limit=100&franBeslutDatum=2021-06-29&tillBeslutDatum=2021-08-29')"
```

If I persist the file locally using curl, piping the content to 'test.json' and then use https://shell.duckdb.org/ with the `.files add` command, the statement `from 'test.json` then works there.

I then tried with another API request which returns json. Again it works in the CLI but both shell.duckdb.org and sql-workbench complains:

```
# this command works
duckdb -c "from read_json_auto('https://api.openalex.org/works?page=1&filter=authorships.author.id:a5002018805') select unnest(results, recursive := true)"

#error message in shell.duckdb.org and sql-workbench.com
Invalid Input Error: Malformed JSON in file "https://api.openalex.org/works?page=1&filter=authorships.author.id:a5002018805", at byte 2220 in record/value 2: unexpected end of data. 
```
This might be unrelated but I started to feel like there is some differences in the json extension between WASM-versions and the CLI.

**Comment by mskyttner** [comment]
Hmmm... I noticed a HEAD request, could  the "unexpected end of data" be due to attempting to reading from the HEAD request (which may have no content, which is perfectly ok, if I understand correctly)? But maybe that is another unrelated issue?

**Comment by tobilg** [comment]
Thanks, can you please make sure you do a hard reload of the SQL Workbench? I think it's a local caching issue...

For me, this seems to work: https://sql-workbench.com/#queries=v0,SELECT-*-FROM-read_json('https%3A%2F%2Fapi.openalex.org%2Fworks%3Fpage%3D1%26filter%3Dauthorships.author.id%3Aa5002018805'%2C-auto_detect%3Dtrue)~

**Comment by mskyttner** [comment]
I confirm that it works when I use chromium. Maybe I cannot figure out how to do that hard reset when using firefox.... 

Right now it works fine also on shell.duckdb.org when using chromium but in firefox I get:

```
Invalid Input Error: Malformed JSON in file "https://api.openalex.org/works?page=1&filter=authorships.author.id:a5002018805", at byte 2220 in record/value 2: unexpected end of data. 
```
I tried also [carbonyl](https://github.com/fathyb/carbonyl) which uses the chromium engine and it worked there.

I then tried running a [containerized variant of firefox](https://github.com/jlesage/docker-firefox) and it complains about the same thing:
![image](https://github.com/user-attachments/assets/d35b0d05-78f1-4a17-952f-b756a1c684e2)

Since the containerized variant of firefox should be sandboxed and pristine, I wonder if there perhaps is an issue when using firefox to open the link you provided?

**Comment by mskyttner** [comment]
The "displaying structs" works. I seem to be having some possibly unrelated issues with getting read_json_auto to work in firefox and with using "unnest" with recursive set to true. I close this now and will try to follow up on those other things in another context.
