### ISSUE TITLE
sql.quacking.cloudInterface: left column resizable?

### ISSUE THREAD

**Issue by ericemc3** [tobilg/sql-workbench#2]
Would be useful to read column names entirely:
![image](https://github.com/tobilg/sql-workbench/assets/17407796/291e82fa-10c0-4ea5-9edf-df7ed72d1840)

**Comment by tobilg** [comment]
I enlarged the left column a bit, implementing resizability takes a litte more effort. For now, you can always right-click on the table name, then "Scripts" -> "Create SELECT". This will generate a SQL select statement with all the column names:

![Bildschirmfoto 2024-02-18 um 17 37 37](https://github.com/tobilg/sql-workbench/assets/1841985/8e6e606f-b57d-4e2d-841f-3f99b848989e)

![Bildschirmfoto 2024-02-18 um 17 37 53](https://github.com/tobilg/sql-workbench/assets/1841985/ead94605-2577-4e23-b613-43e3efc6800e)
