### ISSUE TITLE
Seems to be impossible to copy / paste a value from a "cell" in the datagrid?

### ISSUE THREAD

**Issue by maurice1408** [tobilg/sql-workbench#20]
I cannot find a way to copy a value from the Datagrid - for example back into a where clause? Am I missing something obvious? Mouse selection of a value does not seem to work. 😕

**Comment by tobilg** [comment]
Thanks for reporting, I‘ll have a look

**Comment by tobilg** [comment]
I'll update to the latest perspective version, that enables copy & paste as in the video of https://github.com/finos/perspective/pull/2618#issue-2299491175

**Comment by tobilg** [comment]
It’s using Perspective v3 now, please check if this is resolved

**Comment by maurice1408** [comment]
This does now seem to be resolved. Copy is enabled by selecting "Text Edit" rather than "read only". Thanks!
