### ISSUE TITLE
Circumvent CORS policy

### ISSUE THREAD

**Issue by alexanderhupfer** [tobilg/sql-workbench#5]
`runtime_browser.ts:290 Access to XMLHttpRequest at 'https://storage.googleapis.com/.......' from origin 'https://sql-workbench.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Alternatively, I could probably upload the file into the browsers local-storage

**Comment by alexanderhupfer** [comment]
How about uploading a file manually into local storage?

**Comment by tobilg** [comment]
CSVs, Parquet and Arrow files can already be uploaded via Drag and drop. What file Formats are you interested in?

**Comment by alexanderhupfer** [comment]
Oh cool, that solves the issue. Maybe make this more obvious
