### ISSUE TITLE
Execute code without highlighting it first

### ISSUE THREAD

**Issue by alexanderhupfer** [tobilg/sql-workbench#6]
I think highlighting code is cumbersome. It would be nice to be able to just execute the statement which has the cursor like in TablePlus

**Comment by tobilg** [comment]
Thanks for reporting. Running the query between semincola could work. Still, I need the possiblity to run more than one query (but not all), so the selection mechanism needs to be enabled (as well)… Will look into it

**Comment by alexanderhupfer** [comment]
FYI: that's how TablePlus does it:
<img width="358" alt="image" src="https://github.com/tobilg/sql-workbench/assets/5372632/3051897b-83e5-4c6c-b174-cee225dd85b7">

**Comment by tobilg** [comment]
This is resolved now. If you Hit Ctrl-/Cmd-Enter now and your cursor is at a query, it‘ll run that query
