### ISSUE TITLE
Can't read full column or table name when names exceed width of side-bar

### ISSUE THREAD

**Issue by alexanderhupfer** [tobilg/sql-workbench#8]
<img width="281" alt="Screenshot 2024-03-25 at 16 18 39" src="https://github.com/tobilg/sql-workbench/assets/5372632/e2db51fa-a82f-4da8-8adc-7191759c5616">

Possible Solution: Ability to make sidebar wider or/and show full name on mouseover

**Comment by tobilg** [comment]
This is now fixed. Please check... Thanks!
